### ISSUE TITLE
Repo gamejolt/gamejolt: npm dependency doesn't compile native-lzma

### ISSUE THREAD

**Issue by luckcolors** [gamejolt/issue-tracker#493]
Hello guys.
I tried resolving npm dependencies (npm i) and it works but i encountered an build error in the log.
Apparently it happens becuase some dependency is using an old version of native-lzma.
I discussed the issue with the package dev here: https://github.com/addaleax/lzma-native/issues/12
Also node-gyp and node-pre-gyp doesn't seem to be packages which are already installed by default by nvm so i suggest adding those to the required packages list will help.
Here is my build log: 
[npm-debug.zip](https://github.com/gamejolt/issue-tracker/files/90460/npm-debug.zip)

**Comment by addaleax** [comment]
I created a PR add gamejolt/client-voodoo#13, since that seems to be the dependency @luckcolors was talking about.

> Also node-gyp and node-pre-gyp doesn't seem to be packages which are already installed by default by nvm so i suggest adding those to the required packages list will help.

[node-pre-gyp](https://github.com/mapbox/node-pre-gyp) is a dependency of `lzma-native@1.x.x`, it does not need to be installed separately. [node-gyp](https://github.com/nodejs/node-gyp) should come bundled with Node.js, as it is a dependency of npm, and it’s unusual to include it as a dependency of its own.

I don’t exactly know what the problem in addaleax/lzma-native#12 was (I’d guess something wrong with node-gyp and/or a missing compiler toolchain, nodejs/node-gyp#629 says hello), but using `lzma-native@1.x.x` with its pre-built binaries seems to have been a solution.

**Comment by YLivay** [comment]
Hey, thanks! We'll try building with the newer version :)

**Comment by hworld** [comment]
Hey, I pulled in the new version of lzma-native. Is this working any better for you @luckcolors? It should be updated in the https://github.com/gamejolt/gamejolt repo.

**Comment by luckcolors** [comment]
Ok now native-lzma builds correctly as confirmed by the log here:
Also there seems now to be some postinstall error of some deps but as before npm exits correctly and resolves the deps.
```
npm WARN install Couldn't install optional dependency: Unsupported //right appdmg is probably for mac only
npm WARN deprecated gulp-clean@0.3.1: use gulp-rimraf instead
npm WARN deprecated gulp-minify-css@0.3.13: Please use gulp-cssnano instead.
npm WARN deprecated lodash@1.2.1: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

> lzma-native@1.0.3 install C:\Users\luckcolors\Desktop\gamejolt\node_modules\lzma-native
> node-pre-gyp install --fallback-to-build

[lzma-native] Success: "C:\Users\luckcolors\Desktop\gamejolt\node_modules\lzma-native\binding\lzma_native.node" is installed via remote

> optipng-bin@3.0.4 postinstall C:\Users\luckcolors\Desktop\gamejolt\node_modules\optipng-bin
> node lib/install.js

C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159:9)
    at Transform._read (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:600:7
    at nextTickCallbackWith0Args (node.js:452:9)
npm WARN install:optipng-bin@3.0.4 optipng-bin@3.0.4 postinstall: `node lib/install.js`
npm WARN install:optipng-bin@3.0.4 Exit status 1

> jpegtran-bin@3.0.6 postinstall C:\Users\luckcolors\Desktop\gamejolt\node_modules\jpegtran-bin
> node lib/install.js

C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159:9)
    at Transform._read (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:600:7
    at nextTickCallbackWith0Args (node.js:452:9)
npm WARN install:jpegtran-bin@3.0.6 jpegtran-bin@3.0.6 postinstall: `node lib/install.js`
npm WARN install:jpegtran-bin@3.0.6 Exit status 1

> gifsicle@3.0.3 postinstall C:\Users\luckcolors\Desktop\gamejolt\node_modules\gifsicle
> node lib/install.js

C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159
  throw new Error('not implemented');
  ^

Error: not implemented
    at Transform._transform (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:159:9)
    at Transform._read (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at Transform.Writable.write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at C:\Users\luckcolors\Desktop\gamejolt\node_modules\readable-stream\lib\_stream_readable.js:600:7
    at nextTickCallbackWith0Args (node.js:452:9)
npm WARN install:gifsicle@3.0.3 gifsicle@3.0.3 
```

**Comment by addaleax** [comment]
(@luckcolors – I guess this has nothing to do with my lzma-native module anymore, but I really feel like an uploaded npm-debug.log might be helpful here again :smile:)

**Comment by luckcolors** [comment]
Oh i haven't uploaded it becuase it wasn't generated by npm.
i'll re run the npm install with -dd

**Comment by hworld** [comment]
How did you install node-gyp build stuff on windows? The only thing that worked for me is to follow the instructions exactly on the node-gyp package: https://github.com/nodejs/node-gyp

**Comment by luckcolors** [comment]
Ah right @hworld. My windows install was pretty new so i forgot to install python 27.
All the problems are now solved thanks for you patience and support guys. :)

**Comment by hworld** [comment]
Perfect! I remember just how much of a nightmare it was. I think the first time I tried I installed python3 and then later got bit by that decision. It's so finicky.
