### ISSUE TITLE
IndexedDB acting up

### ISSUE THREAD

**Issue by YLivay** [gamejolt/issue-tracker#587]
User's been getting some weird issues with IndexedDB.

Related logs:
log#27

```
{ message: 'Internal error opening backing store for indexedDB.open.',
name: 'UnknownError',
toString: [Function] }
```

log#22

```
{ message: 'Failed to execute \'transaction\' on \'IDBDatabase\': One of the specified object stores was not found.',
name: 'NotFoundError',
code: 8,
stack: 'Error: Failed to execute \'transaction\' on \'IDBDatabase\': One of the specified object stores was not found.\n at Error (native)\n at app://game-jolt-client/package/app/modules/client.js:1:18888\n at h (app://game-jolt-client/package/app/modules/client.js:2:5938)\n at new r (app://game-jolt-client/package/app/modules/client.js:2:4324)\n at app://game-jolt-client/package/app/modules/client.js:1:18685\n at Function.r.newPSD (app://game-jolt-client/package/app/modules/client.js:2:7759)\n at V.r._promise (app://game-jolt-client/package/app/modules/client.js:1:18540)\n at H.i [as _tpf] (app://game-jolt-client/package/app/modules/client.js:1:3981)\n at H._idbstore (app://game-jolt-client/package/app/modules/client.js:1:14293)\n at H.get (app://game-jolt-client/package/app/modules/client.js:1:14414)' }
```

**Comment by hworld** [comment]
Have we ever seen this lately?

**Comment by YLivay** [comment]
I've just seen that in log#92. It may have something to do with large files?

**Comment by hworld** [comment]
Gonna close this until we see it again in logs. We upgraded dexie in newest client.
